### PR TITLE
Added 6 mods for 1.8 and 10 mods for 1.7.10

### PR DESCRIPTION
**Pull request by Adaptivity**
Also changed some dependencies: 1) if mod depend on Thaumcraft 4, it "depend" on Baubles too (Because Thaumcraft 4 depends on Baubles, so no need to add Baubles to all Thaumcraft 4 addons). 
2) CoFH mods doesn't depend on CoFH Lib. Thermal Foundation depends on CoFH Core -> Thermal Expansion 4 depends on Thermal Foundation, so TE 4 "doesn't depend" on CoFH Core because Thermal Foundation already requires it.

Some descriptions are missing as always.

### CODE REVIEW

**Comment by GrygrFlzr** [comment]
That was on purpose, though, as they are still indirect dependencies. It would be frustrating for people to check FLORA, get the listed dependency (Redstone Arsenal), realize it needs Thermal Foundation and _then_ find out it needs CoFH Core. See [dependency hell](https://en.wikipedia.org/wiki/Dependency_hell).
It does mean it's nicer to edit when one of the lower dependencies (like CoFH Core) gains its own dependency, as you only need to modify one entry. I'd need to code some sort of automatic dependency resolver though. Might have to discuss with someone more knowledgeable with databases.

**Comment by Adaptivity** [comment]
You can revert changes about dependencies but in my opinion they are a bit nicer.

**Comment by Adaptivity** [comment]
Also, new Atum link: http://www.minecraftforum.net/forums/mapping-and-modding/minecraft-mods/2373722-atum-journey-into-the-sands

**Comment by GrygrFlzr** [comment]
My computer is being silly with the Internet connection, so this might take longer than expected.

**Comment by Adaptivity** [comment]
Merge it when you ready. No rush :D

**Comment by Adaptivity** [comment]
Updated again, you might want to add this too: http://www.minecraftforum.net/forums/mapping-and-modding/minecraft-mods/1285356-list-of-mods-for-1-8?comment=2883

**Comment by GrygrFlzr** [comment]
I'm removing MiscPeripherals as all of its download links are dead. It does have a download for its source code in the last post of the thread, but considering the lack of maintenance and the existence of Peripherals++, its removal is justified.
Dependencies have been reverted for now, hopefully in the future we won't have to manage those manually. It would be nice to be able to see which are direct and transient dependencies.

**Pull request merged**
