### PR TITLE
April Update

### PR DESCRIPTION
**Pull request by Adaptivity**
~~Missed dependency for Werkbench -> CodeChickenCore. - No longer depend on it.
Also, I forgot about http://minecraft.curseforge.com/mc-mods/228865-switches-continued~~

### CODE REVIEW

**Comment by Adaptivity** [comment]
@GrygrFlzr if you are ready to pull it, don't pull it. I have few changes on local setup, not sure when I'll complete them.

**Comment by Adaptivity** [comment]
Should be done for some time. Some descriptions needs changes.

**Comment by GrygrFlzr** [comment]
Alright. I probably won't be able to finalize it until next week-ish, I've been on back-to-back plane trips for a bit. :v

**Comment by Adaptivity** [comment]
It's ok. Take your time. Have a nice trip :smile:

**Comment by Adaptivity** [comment]
Rolled another package of mods. I've checked MCF thread a bit and it would be cool if some posts can be deleted. Can you talk to moderators about it?
Notable:
1) Posts by ashdjtgfoe (Ashmod collections? Its some kind of modpack or what? Some of them not free.....)
2) Post number 2911
3) Post number 2893 (There was some ads I guess)
4) Post number 2890

**Comment by GrygrFlzr** [comment]
Just report those with the MCF report button, I don't have more access than you do. :P

**Comment by Adaptivity** [comment]
But you are usually at IRC I guess. So, I think it will be faster if you ask :D

**Comment by GrygrFlzr** [comment]
Actually, no, I asked to rename the modlist thread for 1.8 once and they told me to use the report button. :v
MCF works a bit strangely.

**Comment by ZeroLevels** [comment]
Wondering why this pull request is still sitting here.  Is there something else that needs to be done before it can be merged, or is it good to go?

**Comment by GrygrFlzr** [comment]
Slight JSON formatting issues (if you merge this now the site will go down), some missing descriptions to write and descriptions to rewrite.
Maybe I should make a staging branch so everyone can work on those. :v
Will do that when I get to school and we can work on it together I suppose.

**Comment by GrygrFlzr** [comment]
Change of plans going forward, since I can't seem to keep up anymore and grade 12 is coming up.
@Adaptivity, if you're still interested in updating the modlist, feel free to submit more PRs. I no longer have the time to really maintain the list, so I can't really do descriptions anymore. I only have time to fix any JSON formatting issues and then I'll just push it immediately.
Thank you very much for doing all this work, I'm really sorry it took this long for merely 4 lines of changes.

**Comment by Adaptivity** [comment]
Will see if I can find some time to add new mods. No promises though.

**Pull request merged**
