### PR TITLE
A bunch of mods

### PR DESCRIPTION
**Pull request by Adaptivity**

### CODE REVIEW

**Comment by GrygrFlzr** [comment]
I was _just_ about to go to bed, nice timing!

**Comment by Adaptivity** [comment]
Can you add tterrag1098 to Chisel 2 devs? And possibly delete Shape shifter link here: http://modlist.mcf.li/panel/submission

**Comment by GrygrFlzr** [comment]
Done for both.

**Comment by Adaptivity** [comment]
Thanks.

**Pull request merged**
