### PR TITLE
Add MIT License

### PR DESCRIPTION
**Pull request by GrygrFlzr**
This is to get rid of any ambiguity in what people can do with the project.
Requesting confirmation from @ZeroLevels, @Adaptivity, and @citricsquid (although the latter probably would agree considering commit 40c71ae in the database branch).
Unsure about author formatting (should we use MCFModlist instead of listing out everyone?) and whether or not changes to modlist.json even count as copyrightable data, considering that stuff should normally be in a database (probably does, since we still commited it).

### CODE REVIEW

**Comment by Adaptivity** [comment]
I'm ok with it.

**Comment by citricsquid** [comment]
:+1:

**Comment by Adaptivity** [comment]
@ZeroLevels where are you? :smile:

**Comment by Adaptivity** [comment]
Anything on this? Or we should wait for that forever? :D

**Comment by GrygrFlzr** [comment]
It is possible to have this legally complete by making sure every line @ZeroLevels wrote is replaced, but if modlist.json and the changelogs (data which is normally in a database) count, then it might be practically impossible until migration to a database. Not a lawyer though. I'm unsure how to proceed without his blessing.

**Comment by Adaptivity** [comment]
Can you try to contact him through IRC or twitter? If you not done it yet.

**Comment by ZeroLevels** [comment]
Considering I know very little about this, perhaps give me the run-down of what would change should this license come into play.

**Comment by GrygrFlzr** [comment]
This is a summary from GitHub's [ChooseALicense.com](http://choosealicense.com/) project:
> It lets people do anything they want with your code as long as they provide attribution back to you and don’t hold you liable.

This allows:
- Commercial use
- Distribution
- Modification
- Private Use
- Sublicensing (other people who fork our project can in turn allow others to modify/distribute theirs, etc.)

Mostly applies to code, I'd say the actual list of mods itself is an asset (although we are basically giving it away anyway, so no harm there).

As an aside, I'm thinking of changing the list of names into just "Copyright (c) 2013-2015 MCF Modlist" for brevity.

**Comment by ZeroLevels** [comment]
Okay.  Well, go for it then.  Or do you want me to hit the merge button?  Either way, you're good to go.

**Pull request merged**
