### PR TITLE
Massive update 6

### PR DESCRIPTION
**Pull request by Adaptivity**
Preview of massive update 6, don't merge till sunday. I might add some extra mods.
Changelog:
1) Tons of new mods.
2) Various updates for current mods, plus removed some dead mods.
3) Added some Japanese mods. Descriptions needed.
4) Descriptions needed for: Dimensional Pockets, Monster Girl Mod, Aesthetics, Integrated Circuits, Magia Naturalis, Netherrocks, Scott's Tweaks (Apple & Milk & Tea can be better?)
Should be last update for february but who knows.
Also, why MCF thread was unstickied?

### CODE REVIEW

**Comment by GrygrFlzr** [comment]
Unsure why MCF thread was unstickied. Asked the MCF IRC channel about it but there was not really a response.
Will hold off until Sunday. There's also this new mod, I can add it if you're too busy:
http://www.minecraftforum.net/forums/mapping-and-modding/minecraft-mods/wip-mods/2352247-integrated-circuits-alpha-ics-for-minecraft

**Comment by Adaptivity** [comment]
I'll add it and everything from todo later today. You can start work on descriptions :smile:

**Comment by Lunatrius** [comment]
Monster Spawn Highlighter on 1.7.10 won't be updated for 1.8 either.
*Note: there will (hopefully soon) be a successor mod however.*

**Comment by Adaptivity** [comment]
Thanks for note.

**Comment by Adaptivity** [comment]
Should be done expect descriptions.

P.S http://i.imgur.com/vtI8buh.jpg hate these guys a lot.

**Comment by Adaptivity** [comment]
It might worth to delay update to next weekend. I plan to make some alphabetic changes in changelogs. And of course add some more 1.8 mods. @GrygrFlzr just do some description magic :smile:

**Comment by Adaptivity** [comment]
This update probably will be biggest in the modlist history:
1.8 changelog: http://pastebin.com/2sDHribM
1.7.10 changelog: http://pastebin.com/m17E8ZXY (82 mods added :smile: )
I'll probably push it in the saturday morning. No additional descriptions required except those in the first message.

**Comment by GrygrFlzr** [comment]
[Mouse Tweaks](http://www.minecraftforum.net/forums/mapping-and-modding/minecraft-mods/1286379-1-7-10-ssp-smp-mouse-tweaks-2-4-4) is available for 1.8, and Lunatrius just published [Laser Level](https://mods.io/mods/1123) for 1.8.

**Comment by Adaptivity** [comment]
Both added.
1.8 changelog: http://pastebin.com/uJ36K81N
1.7.10 changelog: http://pastebin.com/MtQsiagY (92 mods, can we get 100? :smile: )

**Comment by GrygrFlzr** [comment]
Where's the commit? :P

**Comment by Adaptivity** [comment]
Now it's done for real. Hope you have some free time to pull it today.

**Comment by GrygrFlzr** [comment]
Thank you so much for all your work.

**Pull request merged**
